{% set name = "pycparser" %}
{% set version = "2.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 491c8be9c040f5390f5bf44a5b07752bd07f56edf992381b05c701439eec10f6

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
    # used by tests
    - examples  # [linux]
    # contains fake libc includes which bypasses errors which occurs when including real system headers
    - utils  # [linux]
  imports:
    - pycparser
    - pycparser.ply
  requires:
    - pip
    - python
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --rootdir=. -vv tests

about:
  home: https://github.com/eliben/pycparser
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Complete C99 parser in pure Python
  description: |
    pycparser is a complete parser of the C language, written in pure Python using the PLY parsing library.
    It parses C code into an AST and can serve as a front-end for C compilers or analysis tools.
  dev_url: https://github.com/eliben/pycparser
  doc_url: https://github.com/eliben/pycparser

extra:
  recipe-maintainers:
    - synapticarbors
