# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "v8poragHXU3KfUXPiHt9xWka0TbQNeWa63D6tZ2FDXXuEvcimqjLWFPlW3Bx67Wz9jOqIaSBJrWCpqdTPKB0xjz5qeLGJ/5ZAateouuIhQA7IV5ODojOLtDmKUDwh0S0USs6YOeTVZID4XuWI4c/hFuSXYKg+c7oIF3da2wRPA0kcB26aS82ipXMd+ru2yTg1xVWWQUfQuCuZMuAsdNAS/Mm7UNkv6GmC/CIvTt+UfSbUCN10LPC6ByxtGots0rI3qWRSEzDEQAtFhJZbvMncxWzgLOkgvZtuVtM2fgUjJm/1oSm39fAD0bd8ew/8T0m6wTRXORkv88SwswJGvfqjgyLixqqtCMVDezmng7wTBJybT2d9OsiiUXbx1XgxgEQg51j8Nn1fPOpUovEwWw/yVlAvTG4Qwo22vTBYg6PaJBoZYo9xIf8mjt1Ae2pY529RLY7kXKQjo6QuW5elExFJolCLseT1Xr49qAjTX/1l9Z/YrXRV6mmD3u/kbYVmupaNd+adKtqSuGIRdMPIOoR6pONsYSGsBGNxl38/lu0RsjkIVDqXYmos0xEcdRwsyAzWBOhHAZkiTXg7V8VCCgirsFsp6drBXkohI6a4UZQWtUl98qoFKZ0ACmtgvM/oaQLRdE2iSkOzrRGFQpRx7A53ZSMYtcKkl0O8xalcVywCcM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
