travis:
  secure:
    BINSTAR_TOKEN: v8poragHXU3KfUXPiHt9xWka0TbQNeWa63D6tZ2FDXXuEvcimqjLWFPlW3Bx67Wz9jOqIaSBJrWCpqdTPKB0xjz5qeLGJ/5ZAateouuIhQA7IV5ODojOLtDmKUDwh0S0USs6YOeTVZID4XuWI4c/hFuSXYKg+c7oIF3da2wRPA0kcB26aS82ipXMd+ru2yTg1xVWWQUfQuCuZMuAsdNAS/Mm7UNkv6GmC/CIvTt+UfSbUCN10LPC6ByxtGots0rI3qWRSEzDEQAtFhJZbvMncxWzgLOkgvZtuVtM2fgUjJm/1oSm39fAD0bd8ew/8T0m6wTRXORkv88SwswJGvfqjgyLixqqtCMVDezmng7wTBJybT2d9OsiiUXbx1XgxgEQg51j8Nn1fPOpUovEwWw/yVlAvTG4Qwo22vTBYg6PaJBoZYo9xIf8mjt1Ae2pY529RLY7kXKQjo6QuW5elExFJolCLseT1Xr49qAjTX/1l9Z/YrXRV6mmD3u/kbYVmupaNd+adKtqSuGIRdMPIOoR6pONsYSGsBGNxl38/lu0RsjkIVDqXYmos0xEcdRwsyAzWBOhHAZkiTXg7V8VCCgirsFsp6drBXkohI6a4UZQWtUl98qoFKZ0ACmtgvM/oaQLRdE2iSkOzrRGFQpRx7A53ZSMYtcKkl0O8xalcVywCcM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
